#!/bin/sh
seed=`head -c 2 /dev/urandom | hexdump -e '"%u"'`
timelimit="--time-limit=10"
#timelimit=""
mkdir -p out
. ./sources
if [ $# -gt 0 ]
then
  constraints="$*"
fi
sources="$sources $constraints"
echo $seed > out/seed
echo "Sources:"
echo $sources
echo "% vim"": syn=gringo" > out/source
cat $sources >> out/source


echo "% vim"": syn=gringo" > out/grounded
echo "---"
echo "Running: \"gringo -t $sources\""
time --format="%E, %K KB" gringo -t $sources >> out/grounded
echo "  ...done."


echo "% vim"": syn=lua" > out/stats
echo "---"
echo "Running: \"clingo --stats $timelimit $args $sources\""
time --format="%E, %K KB" \
  clingo --stats $timelimit $args $sources |\
  tail -n 29 | head -n -1 >> out/stats
echo "  ...done."


echo "% vim"": syn=gringo" > out/events
echo "---"
echo "Running: \"clingo --verbose=0 --quiet=1,1 $args $sources\""
time --format="%E, %K KB" \
  clingo --verbose=0 --quiet=1,1 $args $sources |\
    cat | head -n 1 | sed "s/)$/)./" | sed "s/) /).\n/g" |\
    sed "s/^\([a-zA-Z0-9_]\+\)$/\1./" | sort >> out/events
echo "  ...done."


echo "% vim"": syn=gringo" > out/core
grep "story_node(" < out/events >> out/core
echo "" >> out/core
grep "^setup(" < out/events >> out/core
echo "" >> out/core
grep "action(option" < out/events >> out/core
echo "" >> out/core
grep "arg(option" < out/events >> out/core
echo "" >> out/core
grep "outcome(option" < out/events >> out/core
echo "" >> out/core
grep "consequence(option" < out/events >> out/core
echo "" >> out/core
grep "emphasizes(option" < out/events >> out/core
