#!/bin/sh
core="
core.lp
actions.lp
the_party.lp
actors.lp
setup.lp
grow.lp
items.lp
settings.lp
vignettes.lp
skills.lp
potential.lp
goals.lp
choice_structure.lp
eval.lp
"
core=`echo $core | tr "\n" " "`
content="content/*.lp content/*/*.lp"
#content="content/a-testfour.lp content/p-* content/g-* content/s-* content/*/*.lp"
#content="content/a-testfour.lp"
utils="../utils.lp"
#utils=""
surface="surface.lp"
#surface=""
constraints="test.lpt"
sources="$utils $core $surface $content"
args="--seed=$seed --rand-freq=0.05"
#args="--seed=$seed --rand-freq=0"
