#!/bin/sh
core="
choice_structure.lp
core.lp
eval.lp
grow.lp
items.lp
potential.lp
settings.lp
setup.lp
skills.lp
symbols.lp
the_party.lp
vignettes.lp
"
core=`echo $core | tr "\n" " "`
content="content/*.lp"
surface="surface.lp"
constraints="test.lpt"
sources="../utils.lp $core $surface $content"
args="--seed=$seed --rand-freq=0.05"
