#!/bin/sh
actions="actions.lp"
core="core.lp choice_structure.lp"
surface="english.lp surface.lp"
sources="test.lp utils.lp $core $actions $surface"
finish_sources="out/events.lp utils.lp finish.lp"
args="--seed=$seed --rand-freq=0.5"
